### ISSUE TITLE
Porting to Teensy++2.0

### ISSUE THREAD

**Issue by kaezone** [apmorton/Teensy360#1]
Hi,
I'm looking for a way to flash a 16MB XB360 NAND using a Teensy++2.0, however this project is targeting the 3.0. Would it be possible to port it to the ++2.0?

**Comment by apmorton** [comment]
While it may _technically_ be possible to produce equivalent code for a teensy++ 2.0, the code in this project is very specific to the teensy 3.x platform since we make custom modifications to the teensy code for the custom usb communications protocol we are emulating.

I do not have a teensy++ 2.0 on hand to work with, and no time to work on this project even if I had one.

On an unrelated note:
While the code in this repo does work the last I checked - I would suggest prospective users stick to a more widely used and tested piece of flashing hardware if they don't have the tools required to independently verify the NAND image dumped using this tool (as in another NAND flasher).  This firmware was largely implemented as a proof of concept to see exactly how fast the xbox 360 NAND could be read over SPI.
